### ISSUE TITLE
Most things aren't working on tree.taiga.io when using the Tor Browser.

### ISSUE THREAD

**Issue by herbsmn** [taigaio/taiga-front#1070]
Hey @superalex. If you need anything else, let me know. I hope this is the right place to post.

**Comment by herbsmn** [comment]
This ticket is a result of a convo at https://github.com/taigaio/taiga-front/issues/653#issuecomment-230397266

**Comment by superalex** [comment]
Hello @herbsmn 

We have checked this with our IT team and there is no filtering related to Tor networks.

**Comment by herbsmn** [comment]
Thanks for checking that out. So this is likely an issue with my account or my browser, i'm assuming? Do you guys test functionality with the Tor Browser?

**Comment by superalex** [comment]
I assumed your account is working properly in another browser, we support the last two releases from the most common browsers (firefox, chrome, IE, safari...). We don't test on Tor browser but as it's based on the last firefox releases it should be working properly.

Could you check your javascript console?

**Comment by herbsmn** [comment]
I use Tor Browser as my only browser and have used it on a lot of different websites throughout the years and have never seen a site respond so poorly to my browser choice unless they're blocking Tor IPs. Like you said, it's very much based on Mozilla's Firefox and, because of that, works on most any website.

I can navigate around the site all that I want to, but when I try to like or follow a project or make a new project it just errors out. I checked my javascript console and it didn't show anything at all.

![screenshot1](https://cloud.githubusercontent.com/assets/8562898/16610019/caa08cb8-4347-11e6-9126-cbcfe4a84c46.png)

**Comment by superalex** [comment]
We are not blocking any Tor IPs, you could also check the network tab to see what kind of error you are receiving exactly when your requests fail.

**Comment by herbsmn** [comment]
sry for the delayed response. this is still an issue. 
![hh](https://cloud.githubusercontent.com/assets/8562898/18567494/f09aaff2-7b87-11e6-8bb1-26068e2aabc0.png)
![gg](https://cloud.githubusercontent.com/assets/8562898/18567508/fd894318-7b87-11e6-986e-5e0a2c82d276.png)

**Comment by herbsmn** [comment]
not sure why i'm getting an error when i try to simply "like" the taiga project using Tor Browser.

**Comment by herbsmn** [comment]
it also happens when i try to "watch" any project: 

![gjg](https://cloud.githubusercontent.com/assets/8562898/18567661/c20b8eee-7b88-11e6-808b-589d59a32960.png)
