### ISSUE TITLE
Backlog ordering is messed up during reload

### ISSUE THREAD

**Issue by christianlupus** [taigaio/taiga-front#1748]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
I have a project in the hosted instance of tree.taiga.io. In the backlog view I see a bunch of user stories as intended.
When I want to change the order of these (priorizing the stories) this is done correctly in the first moment: The homepage reflects the changes as intended by me.
When I reload the backlog page the order of the user stories is mixed up.

**If the current behavior is a bug, please provide the steps to reproduce.**
In my project I simply have to pull one (specific) user story to the top and reload the page.

**What is the expected behavior?**
The reload operation keeps the order the same as before the reload (and how I priorized the stories).

**Is it happening in taiga.io or in your own instance?**
In taiga.io

**What browser/version are you using?**
Firefox 66.0.5

**Are there any console errors *(Ctrl + F12)* in red?**
No JavaScript errors were found.

**Further remarks:**
- I can provide access to the project but I would avoid to make the project publicly available with read-write permissions (aka publishing some credentials).
- The priorizing is done internally in the database (according to my quick research) in a single column. It looks to me like the value of this column is equal for multiple stories causing them to be sorted by other means. If I push the most upper story down it lands "somewhere" within the backlog stack. As I cannot look into the database itself. But in the expotred JSON there are multiple entries with `backlog_order: 0`.
- This issue seems similar to #1308 but here I cannot work around the problem by reloading.

**Comment by christianlupus** [comment]
Just for testing I installed a docker-based local taiga installation and looked into the database directly. 

I found the following:
```
select id,subject,status_id,backlog_order from userstories_userstory order by backlog_order LIMIT 20;
 id |                    subject                     | status_id | backlog_order 
----+------------------------------------------------+-----------+---------------
 38 | bcache Laptop einrichten                       |        20 |             0
 39 | Schlüssel Server sichern                       |        19 |             0
 40 | Abrechnungen Wohnung machen                    |        20 |             0
 41 | SD Karte neu einrichten Handy                  |        20 |             3
 43 | Bauteile in Partkeepr eintragen                |        19 |             5
 44 | Zisterne erste Iteration erstellen             |        20 |             6
 35 | Platine David erstellen                        |        20 |             7
 36 | Partkeepr installieren                         |        20 |             8
```

I think the problem is the non-unique entries in the backlog_order column.

**Comment by alexhermida** [comment]
@christianlupus fixed in stable and master branch. Thank you!

**Comment by yakky** [comment]
I just tested the stable branch and the issue it's still there. if I move any item in the sprint, it's immediately moved back to its original position: do we have to run any query to fix existing sprints?

**Comment by alexhermida** [comment]
@yakky this issue is related to the backlog list. Are you referring to it or you reproduce it in another area?

**Comment by yakky** [comment]
The use case in #1759 which was marked as duplicated of this

**Comment by christianlupus** [comment]
Is the version running in https://tree.taiga.io the master version? In this case the issue is not resolved.

Or do I need to recover the project somehow if the problem is there already?

**Comment by alexhermida** [comment]
@yakky thank you, it wasn't the same issue. However, we already fixed it also, if can you update your instance to master it must work. We'll merge into `stable` this week.

@christianlupus htts://tree.taiga.io is `stable` branch. We have to deploy it as long as finally, it was two different bugs.

It is possible that you have to move up some user story to the first place in the Backlog and get it back to the previous position to force the reordering.

**Comment by christianlupus** [comment]
@alexhermida I tried it out and moved the very last entry to the top and back in the UI. This seems to solve the problem for projects that have this problem already. I verified this by exporting, locally importing and looking at the databases' entries. The ordering keys seem unique both for backlog and for sprint view (@yakky I think it works, maybe you need to describe your issue more detailed).

Thank you very much for fixing.
