### ISSUE TITLE
Backlog sorting is broken

### ISSUE THREAD

**Issue by FlorianBezagu** [taigaio/taiga-front#261]
We have created a lot of issues and user stories since a couple of weeks but now we have a problem. We can't sort backlog stories as we want. I don't how when exactly it became broken but now, when you drag and drop a story to a specific place in the backlog it will really be placed most of the time 1 or 2 places behind. Or sometimes it's going to be at the bottom or in the middle of the backlog ...

Maybe one column is broken in DB and I can clean all current stories orders with an SQL query ? If it's ok after that why not, but what did we do to have this ... ?

Product owners are not very happy with this bug because they can't really sort the backlog as they want.

Thanks in advance for your answer.

**Comment by superalex** [comment]
Hello @FlorianBezagu,

Are you using your own instance or tree.taiga.io one?, If you have your own instance, user stories have an attribute "backlog_order" that controls that ordering, you could check if it has any strange values. If it's your own instance, what version are using now?

Regards,

**Comment by FlorianBezagu** [comment]
Hello @superalex,

Yes we are using our own instance of tree.taiga.io with version 1.4.0.
I'm going to check `backlog_order` values but with thousands of stories it can be long ...

**Comment by FlorianBezagu** [comment]
I have a lot of `10000` values in `backlog_order` column. Is it normal ?

**Comment by superalex** [comment]
Yes, it's the default value when you are creating a new US.

**Comment by FlorianBezagu** [comment]
Ok, I have other strange values.

I have executed this query :

```sql
SELECT  us1.id, us1.backlog_order
FROM userstories_userstory us1
INNER JOIN userstories_userstory us2 ON  us1."id" <> us2."id"
                                     AND us1.backlog_order = us2.backlog_order
                                     AND us1.backlog_order <> 10000
GROUP BY us1.id
ORDER BY backlog_order;
```

Just a preview of the result :

![capture d ecran 2015-01-20 a 08 21 50](https://cloud.githubusercontent.com/assets/507108/5813423/73f73c90-a07d-11e4-9515-ea4a2cc5e72f.png)

Is it normal that a lot of stories have the same `backlog_order` value ? Is it our problem ?

**Comment by superalex** [comment]
If they are from the same project (column project) and has null value for milestone (milestone column) the should have different values (except for the 10000)

**Comment by FlorianBezagu** [comment]
Ok, so now with this query :

```sql
SELECT  us1.project_id, us1.milestone_id, us1.id, us1.backlog_order
FROM userstories_userstory us1
INNER JOIN userstories_userstory us2 ON  us1.id <> us2.id
                                     AND us1.backlog_order = us2.backlog_order
                                     AND us1.backlog_order <> 10000
                                     AND us1.milestone_id = us2.milestone_id
GROUP BY us1.id
ORDER BY backlog_order, milestone_id;
```

I have this :

![capture d ecran 2015-01-20 a 08 37 58](https://cloud.githubusercontent.com/assets/507108/5813547/aa26cf7c-a07f-11e4-965e-cf8ada05f1bc.png)

**Comment by superalex** [comment]
You should select only the user stories with null milestone, I don't know why you are using an inner join, you could do something like this:
```
SELECT  us1.project_id, us1.milestone_id, us1.id, us1.backlog_order
FROM userstories_userstory us1
WHERE  
	us1.project_id = 1
    AND us1.backlog_order <> 10000
    AND us1.milestone_id IS NULL
ORDER BY backlog_order;
```

BTW some months ago we solved an issue related to reordering the backlog with filters enabled (if an user did that the order could be broken) but your version should allow you to do it (you could check if that commit is applied in your version) -> https://github.com/taigaio/taiga-front/commit/b900118affcb1506316b556d0cf1d01064a5ada3

**Comment by FlorianBezagu** [comment]
When I execute your query I have correct orders but they begin with value `15`.

I don't think it's a problem, is it ?

**Comment by superalex** [comment]
I don't think it's necessary a problem but if they are not too much entries you could try to overwrite the backlog order to one starting in 0.

**Comment by FlorianBezagu** [comment]
I did it but I have same problems after, it was not my problem.

Do you have other clues please ?

**Comment by superalex** [comment]
You could try moving taiga-front and taiga-back to the stable branch (or to master), recompiling the front and checking if your problem is still happening in those situations.

Another option (if you can wait): next week we will be releasing the import/export feature for projects, if you can wait you could export your project, upload it to Taiga, we could check if the bug is still happening, solve it if necessary and you could remove again your project from tree.taiga.io

**Comment by FlorianBezagu** [comment]
Ok, they are already in `stable` branch but you think I can try to move to `master`? Even for a production environment ?

**Comment by superalex** [comment]
Not for a production environment, just for testing if the  issue is related to something solved in master

**Comment by FlorianBezagu** [comment]
Ok, I have only a production environment so I'm not going to try the `master` branch today ;-).

I'll upgrade to the last commit in the `stable` branch and I come back to tell you if my problem is solved.

**Comment by superalex** [comment]
Ok! :+1:

**Comment by FlorianBezagu** [comment]
My problem is still here :'(

I'll wait for next week release to export / import this project for your help.

**Comment by superalex** [comment]
Ok!

**Comment by FlorianBezagu** [comment]
Hi @superalex 

I upgraded our Taiga to version `1.5.0` but the problem persists ...

Can we talk in private to import / export project and check what's wrong for you ?

**Comment by superalex** [comment]
Hi @FlorianBezagu I've written you a private email :)

**Comment by FlorianBezagu** [comment]
Thx I answered you
